import {
  House,
  MessageCircle,
  Folders,
  Bot,
  Grid2X2,
  Music2,
  Headphones,
  CloudSun,
  Sun,
  Palette,
  Code2,
  Terminal,
  Globe,
  Compass,
  Plane,
  MapPin,
  CalendarDays,
  Mail,
  Newspaper,
  ChartNoAxesCombined,
  Activity,
  Camera,
  Film,
  BookOpen,
  Lightbulb,
  Rocket,
  Coffee,
  Moon,
  Gamepad2,
  Zap,
} from "lucide-react";
import type { WorkspaceIconName } from "../lib/workspaceIcons";
const icons = {
  house: House,
  messages: MessageCircle,
  folders: Folders,
  bot: Bot,
  grid: Grid2X2,
  music: Music2,
  headphones: Headphones,
  cloud: CloudSun,
  sun: Sun,
  palette: Palette,
  code: Code2,
  terminal: Terminal,
  globe: Globe,
  compass: Compass,
  plane: Plane,
  map: MapPin,
  calendar: CalendarDays,
  mail: Mail,
  newspaper: Newspaper,
  chart: ChartNoAxesCombined,
  activity: Activity,
  camera: Camera,
  film: Film,
  book: BookOpen,
  lightbulb: Lightbulb,
  rocket: Rocket,
  coffee: Coffee,
  moon: Moon,
  gamepad: Gamepad2,
  zap: Zap,
};
/** Render only allowlisted Lucide glyphs chosen by Jev. */
export function WorkspaceIcon({ name }: { name: WorkspaceIconName }) {
  const Icon = icons[name];
  return (
    <Icon aria-hidden className="size-6 shrink-0" data-workspace-icon={name} />
  );
}
